box: 8.0
close_mosaic: 20
cls: 2.5
copy_paste: 0.15
degrees: 0.0
dfl: 1.5
dropout: 0.0
fl_gamma: 2.0
fliplr: 0.6
flipud: 0.0
hsv_h: 0.02
hsv_s: 0.8
hsv_v: 0.5
label_smoothing: 0.1
lr0: 0.005
lrf: 0.001
mask_ratio: 4
mixup: 0.25
momentum: 0.937
mosaic: 0.8
nbs: 64
overlap_mask: true
perspective: 0.0
scale: 0.7
shear: 0.0
translate: 0.15
warmup_bias_lr: 0.05
warmup_epochs: 5.0
warmup_momentum: 0.8
weight_decay: 0.0008
